- field: "Aging"
  title: "FIGHT AGING!"
  url: "https://www.fightaging.org/"
  description: "A comprehensive resource covering aging biology research and longevity studies."

- field: "Brain development"
  title: "自然感觉刺激对脑发育的影响"
  url: "https://www.cas.cn/kxcb/kpwz/201401/t20140129_4031024.shtml"
  description: "探讨自然环境刺激对大脑发育的影响机制及其重要性。"

- field: "Brain development"
  title: "青少年脑发育的个体差异性"
  url: "https://zhuanlan.zhihu.com/p/307358952"
  description: "分析青少年时期大脑发育的个体差异及其影响因素。"

- field: "Brain development"
  title: "丰富环境对儿童大脑发育的影响"
  url: "https://zhuanlan.zhihu.com/p/532096885"
  description: "研究环境丰富度对儿童大脑发育的重要作用。"

- field: "Mendelian randomization"
  title: "浅谈孟德尔随机化法与经济学研究的渊源"
  url: "https://zhuanlan.zhihu.com/p/507997457/"
  description: "探讨孟德尔随机化方法在经济学研究中的应用。"

- field: "Mendelian randomization"
  title: "孟德尔随机化推断暴露因素与健康结局的因果关系"
  url: "https://www.jianshu.com/p/8ac31267d3d8"
  description: "介绍使用孟德尔随机化方法研究健康因果关系。"

- field: "GWAS"
  title: "GWAS入门文章与书籍推荐"
  url: "https://gwaslab.org/2021/03/30/gwas%e5%85%a5%e9%97%a8%e6%96%87%e7%ab%a0%e4%b8%8e%e4%b9%a6%e7%b1%8d%e6%8e%a8%e8%8d%90/"
  description: "全基因组关联分析（GWAS）的入门资源推荐。"

- field: "scRNA-seq"
  title: "Dictionary learning for integrative, multimodal, and scalable single-cell analysis (video)"
  url: "https://www.youtube.com/watch?v=AHl5V-9dMOI"
  description: "Video tutorial on dictionary learning methods in single-cell analysis."

- field: "scRNA-seq"
  title: "Seurat - Guided Clustering Tutorial"
  url: "https://satijalab.org/seurat/articles/pbmc3k_tutorial.html"
  description: "Official tutorial for single-cell analysis using the Seurat package."

- field: "scRNA-seq"
  title: "awesome-deep-learning-single-cell-papers"
  url: "https://github.com/OmicsML/awesome-deep-learning-single-cell-papers"
  description: "A curated collection of papers on deep learning applications in single-cell analysis."

- field: "scRNA-seq"
  title: "Bioinformatics Training at the Harvard Chan Bioinformatics Core"
  url: "https://hbctraining.github.io/main/"
  description: "Comprehensive bioinformatics training materials from Harvard."

- field: "scRNA-seq"
  title: "Bioinformatics Training at the Harvard Chan Bioinformatics Core (Chinese note)"
  url: "https://wap.sciencenet.cn/home.php?mod=space&do=blog&id=1241283"
  description: "哈佛生物信息学培训材料的中文笔记。"

- field: "Enrichment analysis"
  title: "一文掌握GSEA"
  url: "https://mp.weixin.qq.com/s?__biz=MzI5MTcwNjA4NQ==&mid=2247488358&idx=1&sn=4c1c15b6467ff7f8bd7fe95400bbc1df&scene=21#wechat_redirect"
  description: "基因集富集分析（GSEA）的详细教程。"

- field: "Cell fate transition"
  title: "从基因调控逻辑解码细胞命运决定的基本原理"
  url: "http://cqb.pku.edu.cn/zyli/info/1041/1196.htm"
  description: "探讨基因调控网络在细胞命运决定中的作用机制。"

- field: "Epigenetics"
  title: "表观遗传的遗传与重编程！"
  url: "https://mp.weixin.qq.com/s/r5UzfMlXocgtl3J8clzDlg"
  description: "表观遗传的遗传与重编程！"
  