- field: "Single-cell"
  title: "STAB"
  url: "https://mai.fudan.edu.cn/stab2/"
  description: "STAB2 (Spatio-Temporal Cell Atlas of Brain) provides a landscape of cell types as well as their regional heterogeneity and temporal dynamics across the human and mouse brain"
  paper_url: "https://academic.oup.com/nar/article/52/D1/D1033/7334093"

- field: "Single-cell, AD"
  title: "SEA-AD"
  url: "https://portal.brain-map.org/explore/seattle-alzheimers-disease"
  description: "The Seattle Alzheimer's Disease Brain Cell Atlas"
  paper_url: "https://www.biorxiv.org/content/10.1101/2023.05.08.539485v3"

- field: "Single-cell"
  title: "scRNASeqDB"
  url: "https://bioinfo.uth.edu/scrnaseqdb/"
  description: "Human Single Cell Transcriptome Database"

- field: "Single-cell"
  title: "Azimuth"
  url: "https://azimuth.hubmapconsortium.org/"
  description: "App for reference based single-cell analysis"
  paper_url: "https://doi.org/10.1016/j.cell.2021.04.048"

- field: "Network"
  title: "CellNetdb"
  url: "http://www.bioailab.com:3838/CellNetdb"
  description: "A comprehensive database for cell network analysis"
  paper_url: "https://pubmed.ncbi.nlm.nih.gov/38347596/"

- field: "GWAS"
  title: "SSGAC Data Portal"
  url: "https://thessgac.com/"
  description: "The NHGRI-EBI Catalog of human genome-wide association studies"
  paper_url: "https://www.nature.com/articles/s41588-018-0147-3"

- field: "Single-cell, Brain"
  title: "Brain Cell Atlas"
  url: "https://www.braincellatlas.org/index"
  description: "A comprehensive and unified atlas of the brain that was built across studies, regions, diseases and sequencing platforms"
  paper_url: "https://www.nature.com/articles/s41591-024-03150-z"
