- field: "Bioinformatics tools"
  title: "satijalab"
  url: "https://satijalab.org/"
  masterpiece: "seurat"
  masterpiece_url: "https://github.com/satijalab/seurat"
  description: "Leading lab in single-cell analysis, creators of the Seurat package"

- field: "Bioinformatics tools"
  title: "Sun Lab"
  url: "https://sqsun.github.io/index.html"
  masterpiece: "TDEseq"
  masterpiece_url: "https://github.com/fanyue322/TDEseq"
  description: "Developing statistical methods for genomics research"

- field: "scRNA-seq tools"
  title: "theislab"
  url: "https://github.com/theislab"
  masterpiece: "scvelo"
  masterpiece_url: "https://github.com/theislab/scvelo"
  description: "Pioneers in RNA velocity analysis and single-cell methods"

- field: "Brain Imaging"
  title: "Computational Brain Imaging Group"
  url: "https://sites.google.com/view/yeolab"
  masterpiece: "CBIG"
  masterpiece_url: "https://github.com/ThomasYeoLab/CBIG"
  description: "Specializing in brain imaging analysis and computational methods"

- field: "Gene regulatory network"
  title: "zpliulab"
  url: "https://github.com/zpliulab"
  masterpiece: "scGENA"
  masterpiece_url: "https://github.com/zpliulab/scGENA"
  description: "Developing tools for single-cell gene regulatory network analysis"

- field: "Gene regulatory network"
  title: "netbiolab"
  url: "https://github.com/zpliulab"
  masterpiece: "scHumanNet"
  masterpiece_url: "https://github.com/netbiolab/scHumanNet"
  description: "Research in human gene regulatory networks at single-cell resolution"

- field: "Gene regulatory network"
  title: "aertslab"
  url: "https://github.com/zpliulab"
  masterpiece: "SCENIC"
  masterpiece_url: "https://github.com/aertslab/SCENIC"
  description: "Developers of SCENIC for gene regulatory network inference"

- field: "Gene regulatory network"
  title: "LULAB"
  url: "https://lusystemsbio.northeastern.edu/"
  masterpiece: "Publications"
  masterpiece_url: "https://lusystemsbio.northeastern.edu/publications/"
  description: "Systems biology approach to gene regulatory networks"

- field: "Gene regulatory network"
  title: "The Glass Group"
  url: "https://sites.google.com/a/channing.harvard.edu/kimberlyglass/home"
  masterpiece: "lionessR"
  masterpiece_url: "https://github.com/kuijjerlab/lionessR"
  description: "Network analysis in biological systems"

- field: "Gene regulatory network"
  title: "THE NETWORK ZOO"
  url: "https://netzoo.github.io/"
  description: "Collection of network biology methods and tools"

- field: "R · statistics"
  title: "Yihui Xie"
  url: "https://yihui.org/"
  masterpiece: "Portfolio"
  masterpiece_url: "https://yihui.org/en/vitae/"
  description: "R programming and statistical computing expert"

- field: "Bioinformation"
  title: "Quan Zou"
  url: "http://lab.malab.cn/~zq/"
  masterpiece: "Portfolio"
  masterpiece_url: "http://lab.malab.cn/~zq/"
  description: "Research in bioinformatics and machine learning"

- field: "Bioinformation"
  title: "Feng Zhang"
  url: "https://fzhang.bioinfo-lab.com/"
  masterpiece: "VECTOR"
  masterpiece_url: "https://github.com/jumphone/Vector/"
  description: "Developing computational methods for biological data analysis"

- field: "Similarity Network Fusion"
  title: "Similarity Network Fusion"
  url: "http://compbio.cs.toronto.edu/SNF/SNF/Software.html/"
  masterpiece: "SNFtool"
  masterpiece_url: "https://rdrr.io/cran/SNFtool/man/SNF.html/"
  description: "Methods for integrating multiple data types through network fusion"

- field: "scRNA-seq and gene networks"
  title: "QuaDBio Group"
  url: "https://bsse.ethz.ch/qdb/"
  masterpiece: "Pando"
  masterpiece_url: "https://github.com/quadbio/Pando/tree/main/"
  description: "Quantitative developmental biology and single-cell genomics"

- field: "GWAS"
  title: "GWASLab"
  url: "https://gwaslab.org/"
  description: "Research in genome-wide association studies and genetic analysis"

- field: "Network dynamics"
  title: "ZhiyuanLi lab"
  url: "http://cqb.pku.edu.cn/zyli/index.htm"
  description: "Research in network dynamics and systems biology"

- field: "Brain development"
  title: "丰富环境对儿童大脑发育的影响"
  url: "https://zhuanlan.zhihu.com/p/532096885"
  description: "探讨环境丰富度对儿童大脑发育的影响。"

- field: "Enrichment analysis"
  title: "一文掌握GSEA"
  url: "https://mp.weixin.qq.com/s?__biz=MzI5MTcwNjA4NQ==&mid=2247488358&idx=1&sn=4c1c15b6467ff7f8bd7fe95400bbc1df&scene=21#wechat_redirect"
  description: "详细介绍基因集富集分析（GSEA）的原理和应用。"

- field: "Cell fate transition"
  title: "从基因调控逻辑解码细胞命运决定的基本原理"
  url: "http://cqb.pku.edu.cn/zyli/info/1041/1196.htm"
  description: "探讨基因调控网络在细胞命运决定中的作用。" 