baseURL = "https://mengxu98.github.io/papers-with-code/"
title = "Paper with code"
theme = "hugo-notepadium"
copyright = "©2023 Mengxu."

publishDir = "../docs"

[[params.nav.custom]]
title = "GitHub"
url = "https://github.com/mengxu98/papers-with-code"
