baseURL = "http://localhost:1313/"
title = "Paper with code"
theme = "hugo-notepadium"
copyright = "©2023 Mengxu."

[[params.nav.custom]]
title = "GitHub"
url = "https://github.com/mengxu98/papers-with-code"
